# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PodTest' do

#pod 'AFNetworking', '~> 2.6.0'
pod 'XMPPFramework', '~> 3.6.6'

end

target 'PodTestTests' do

end

target 'PodTestUITests' do

end

