# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'DistanceAndTime' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

#高德地图

pod 'AMapLocation', '~> 2.1.1'
pod 'AMap3DMap', '~> 4.3.0'

  # Pods for DistanceAndTime

  target 'DistanceAndTimeTests' do
    inherit! :search_paths
    # Pods for testing
  end




  target 'DistanceAndTimeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
